# Generated by Django 4.2.7 on 2026-07-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('browser_use_text', 'Browser Use - 文本模式'), ('app_exploration', 'APP AI探索分析')], max_length=20, verbose_name='角色'),
        ),
    ]
