# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0003_alter_aimodelconfig_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptconfig',
            name='prompt_type',
            field=models.CharField(
                choices=[
                    ('writer', '用例编写提示词'),
                    ('reviewer', '用例评审提示词'),
                    ('app_exploration', 'APP AI探索分析提示词'),
                ],
                max_length=20,
                verbose_name='提示词类型',
            ),
        ),
    ]
