# Generated by Django 4.2.7 on 2026-06-24 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_factory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datafactoryrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='datafactoryrecord',
            index=models.Index(fields=['user', '-created_at'], name='data_factor_user_id_7c734a_idx'),
        ),
        migrations.AddIndex(
            model_name='datafactoryrecord',
            index=models.Index(fields=['tool_category'], name='data_factor_tool_ca_c12b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='datafactoryrecord',
            index=models.Index(fields=['tool_scenario'], name='data_factor_tool_sc_820bde_idx'),
        ),
        migrations.AddIndex(
            model_name='datafactoryrecord',
            index=models.Index(fields=['user', 'tool_category'], name='data_factor_user_id_c91ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='datafactoryrecord',
            index=models.Index(fields=['user', 'tool_scenario'], name='data_factor_user_id_580464_idx'),
        ),
        migrations.AddIndex(
            model_name='datafactoryrecord',
            index=models.Index(fields=['user', 'is_saved'], name='data_factor_user_id_454377_idx'),
        ),
    ]
