# Generated by Django 4.2.7 on 2026-07-21 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_factory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=64, verbose_name='账号编号')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='手机号')),
                ('user_id', models.CharField(blank=True, default='', max_length=64, verbose_name='业务用户ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=128, verbose_name='昵称')),
                ('password', models.CharField(blank=True, default='', max_length=256, verbose_name='密码')),
                ('token', models.TextField(blank=True, default='', verbose_name='Token')),
                ('environment', models.CharField(choices=[('test', '测试环境'), ('test1', 'Test1'), ('staging', '预发环境'), ('dev', '开发环境')], default='test', max_length=32, verbose_name='环境')),
                ('business_domain', models.CharField(choices=[('common', '通用'), ('im', 'IM'), ('room', '房间'), ('mic', '麦序'), ('community', '社区'), ('team', '组队')], default='common', max_length=32, verbose_name='业务域')),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '占用中'), ('disabled', '禁用'), ('invalid', '失效')], default='available', max_length=32, verbose_name='状态')),
                ('purpose', models.CharField(blank=True, default='', max_length=128, verbose_name='用途')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='占用时间')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_accounts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_business_accounts', to=settings.AUTH_USER_MODEL, verbose_name='占用人')),
            ],
            options={
                'verbose_name': '业务测试账号',
                'verbose_name_plural': '业务测试账号',
                'db_table': 'data_factory_business_account',
                'ordering': ['environment', 'business_domain', 'account_no'],
                'indexes': [models.Index(fields=['environment', 'business_domain', 'status'], name='data_factor_environ_028e87_idx'), models.Index(fields=['account_no'], name='data_factor_account_d7f25b_idx'), models.Index(fields=['user_id'], name='data_factor_user_id_d9b7c1_idx'), models.Index(fields=['phone'], name='data_factor_phone_a3f17d_idx'), models.Index(fields=['locked_by', 'status'], name='data_factor_locked__8be93e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='businessaccount',
            constraint=models.UniqueConstraint(fields=('environment', 'account_no'), name='uniq_business_account_environment_account_no'),
        ),
    ]
