# Generated by Django 4.2.7 on 2026-07-22 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_factory', '0003_businessaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLoadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('scenario_type', models.CharField(choices=[('room_list_load', '房间列表压测'), ('voice_room_online', '语音房在线保活'), ('room_enter_leave', '进退房压测'), ('community_follow', '关注社区压测')], max_length=64, verbose_name='场景类型')),
                ('environment', models.CharField(choices=[('test', '测试环境'), ('test1', 'Test1'), ('staging', '预发环境'), ('dev', '开发环境')], default='test', max_length=32, verbose_name='环境')),
                ('business_domain', models.CharField(choices=[('common', '通用'), ('im', 'IM'), ('room', '房间'), ('mic', '麦序'), ('community', '社区'), ('team', '组队')], default='room', max_length=32, verbose_name='业务域')),
                ('account_count', models.PositiveIntegerField(default=1, verbose_name='账号数量')),
                ('account_tags', models.JSONField(blank=True, default=list, verbose_name='账号筛选标签')),
                ('purpose', models.CharField(blank=True, default='', max_length=128, verbose_name='用途')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='执行参数')),
                ('capability_chain', models.JSONField(blank=True, default=list, verbose_name='能力链')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='执行指标')),
                ('logs', models.JSONField(blank=True, default=list, verbose_name='执行日志')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('ready', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='draft', max_length=32, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_load_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '业务压测任务',
                'verbose_name_plural': '业务压测任务',
                'db_table': 'data_factory_business_load_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['environment', 'business_domain', 'status'], name='data_factor_environ_178ef4_idx'), models.Index(fields=['scenario_type', 'status'], name='data_factor_scenari_f7c0fc_idx'), models.Index(fields=['created_by', '-created_at'], name='data_factor_created_014b92_idx')],
            },
        ),
    ]
