# Generated by Django 4.2.7 on 2026-06-24 03:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, verbose_name='套件描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'db_table': 'testsuites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSuiteCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='执行顺序')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase')),
                ('testsuite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuites.testsuite')),
            ],
            options={
                'verbose_name': '测试套件用例',
                'verbose_name_plural': '测试套件用例',
                'db_table': 'testsuite_cases',
                'ordering': ['order'],
            },
        ),
    ]
