# Generated by Django 4.2.7 on 2026-06-24 03:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='用例标题')),
                ('description', models.TextField(blank=True, verbose_name='用例描述')),
                ('preconditions', models.TextField(blank=True, verbose_name='前置条件')),
                ('steps', models.TextField(blank=True, max_length=1000, verbose_name='操作步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '激活'), ('deprecated', '废弃')], default='draft', max_length=20, verbose_name='状态')),
                ('test_type', models.CharField(choices=[('functional', '功能测试'), ('integration', '集成测试'), ('api', 'API测试'), ('ui', 'UI测试'), ('performance', '性能测试'), ('security', '安全测试')], default='functional', max_length=20, verbose_name='测试类型')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'testcases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='附件名称')),
                ('file', models.FileField(upload_to='testcase_attachments/', verbose_name='文件')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '测试用例附件',
                'verbose_name_plural': '测试用例附件',
                'db_table': 'testcase_attachments',
            },
        ),
        migrations.CreateModel(
            name='TestCaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '测试用例评论',
                'verbose_name_plural': '测试用例评论',
                'db_table': 'testcase_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_no', models.CharField(max_length=50, unique=True, verbose_name='导入编号')),
                ('import_file', models.FileField(upload_to='testcase_imports/', verbose_name='导入文件')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('importing', '导入中'), ('completed', '已完成'), ('partial_success', '部分成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('skip_count', models.IntegerField(default=0, verbose_name='跳过数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('failure_details', models.JSONField(blank=True, default=list, verbose_name='失败明细')),
                ('failure_report_file', models.FileField(blank=True, null=True, upload_to='testcase_import_failures/', verbose_name='失败明细文件')),
                ('template_version', models.CharField(default='v1', max_length=20, verbose_name='模板版本')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, verbose_name='Celery任务ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '测试用例导入记录',
                'verbose_name_plural': '测试用例导入记录',
                'db_table': 'testcase_import_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='步骤序号')),
                ('action', models.TextField(verbose_name='操作')),
                ('expected', models.TextField(verbose_name='预期结果')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_details', to='testcases.testcase')),
            ],
            options={
                'verbose_name': '测试用例步骤',
                'verbose_name_plural': '测试用例步骤',
                'db_table': 'testcase_steps',
                'ordering': ['step_number'],
            },
        ),
    ]
