# Generated by Django 4.2.7 on 2026-06-24 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versions', '0001_initial'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseimportrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_import_records', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='testcaseimportrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_import_records', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='testcasecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='testcasecomment',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testcases.testcase'),
        ),
        migrations.AddField(
            model_name='testcaseattachment',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='testcases.testcase'),
        ),
        migrations.AddField(
            model_name='testcaseattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_testcases', to=settings.AUTH_USER_MODEL, verbose_name='指派人'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_testcases', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='projects.project'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='testcases', to='versions.version', verbose_name='关联版本'),
        ),
        migrations.AlterUniqueTogether(
            name='testcasestep',
            unique_together={('testcase', 'step_number')},
        ),
    ]
