# Generated by Django 4.2.7 on 2026-06-24 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='版本描述')),
                ('is_baseline', models.BooleanField(default=False, verbose_name='是否为基线版本')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('projects', models.ManyToManyField(related_name='versions', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本',
                'db_table': 'versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
