# -*- coding: utf-8 -*-
"""APP page-map asset views."""

import re

from django.db import transaction
from django.db.models import Count, Q
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.filters import SearchFilter
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .test_case_views import AppPagination
from ..models import AppElement, AppPageElement, AppPageNode, AppPageTransition
from ..serializers import (
    AppElementSerializer,
    AppPageElementSerializer,
    AppPageNodeSerializer,
    AppPageTransitionSerializer,
    _build_page_element_candidate_name,
)


def _is_page_element_ignored(page_element):
    raw = page_element.raw if isinstance(page_element.raw, dict) else {}
    return str(raw.get('governance_status') or '').strip() == 'ignored'


class AppPageMapViewSet(viewsets.ReadOnlyModelViewSet):
    """Read persisted page-map assets generated by controlled inspections."""

    serializer_class = AppPageNodeSerializer
    permission_classes = [IsAuthenticated]
    pagination_class = AppPagination
    filter_backends = [DjangoFilterBackend, SearchFilter]
    filterset_fields = ['project', 'app_package', 'platform', 'activity']
    search_fields = ['title', 'business_name', 'activity', 'page_signature']

    def get_queryset(self):
        queryset = (
            AppPageNode.objects
            .select_related('project', 'app_package', 'first_seen_run', 'last_seen_run')
            .prefetch_related('elements')
            .order_by('-updated_at')
        )
        search = str(self.request.query_params.get('search') or '').strip()
        if search:
            queryset = queryset.filter(
                Q(title__icontains=search)
                | Q(business_name__icontains=search)
                | Q(activity__icontains=search)
                | Q(page_signature__icontains=search)
                | Q(elements__text__icontains=search)
                | Q(elements__content_desc__icontains=search)
                | Q(elements__resource_id__icontains=search)
            ).distinct()
        return queryset

    @action(detail=False, methods=['get'], url_path='summary')
    def summary(self, request):
        queryset = self.filter_queryset(self.get_queryset())
        page_count = queryset.count()
        element_queryset = AppPageElement.objects.filter(page__in=queryset)
        transition_queryset = AppPageTransition.objects.filter(from_page__in=queryset)
        activity_count = queryset.exclude(activity='').values('activity').distinct().count()
        top_pages = (
            queryset
            .annotate(element_total=Count('elements'), transition_total=Count('outgoing_transitions'))
            .order_by('-visit_count', '-updated_at')[:8]
        )
        return Response({
            'success': True,
            'data': {
                'page_count': page_count,
                'activity_count': activity_count,
                'element_count': element_queryset.count(),
                'clickable_count': element_queryset.filter(clickable=True).count(),
                'transition_count': transition_queryset.count(),
                'top_pages': [
                    {
                        'id': page.id,
                        'title': page.business_name or page.title,
                        'activity': page.activity,
                        'visit_count': page.visit_count,
                        'element_count': page.element_total,
                        'transition_count': page.transition_total,
                    }
                    for page in top_pages
                ],
            },
        })

    @action(detail=False, methods=['get'], url_path='element-candidates')
    def element_candidates(self, request):
        queryset = (
            AppPageElement.objects
            .select_related('page', 'page__project', 'page__app_package')
            .filter(enabled=True)
            .order_by('-clickable', '-seen_count', 'page_id', 'id')
        )
        project_id = request.query_params.get('project')
        app_package_id = request.query_params.get('app_package')
        legacy_page_filter = bool(
            request.query_params.get('page')
            and not request.query_params.get('page_id')
            and not request.query_params.get('node_id')
        )
        page_id = request.query_params.get('page_id') or request.query_params.get('node_id') or request.query_params.get('page')
        role = str(request.query_params.get('role') or '').strip()
        search = str(request.query_params.get('search') or '').strip()
        only_clickable = str(request.query_params.get('clickable') or '').lower() in {'1', 'true', 'yes'}
        include_ignored = str(request.query_params.get('include_ignored') or '').lower() in {'1', 'true', 'yes'}

        if project_id:
            queryset = queryset.filter(page__project_id=project_id)
        if app_package_id:
            queryset = queryset.filter(page__app_package_id=app_package_id)
        if page_id:
            queryset = queryset.filter(page_id=page_id)
        if role:
            queryset = queryset.filter(role=role)
        if only_clickable:
            queryset = queryset.filter(clickable=True)
        if search:
            queryset = queryset.filter(
                Q(text__icontains=search)
                | Q(content_desc__icontains=search)
                | Q(resource_id__icontains=search)
                | Q(class_name__icontains=search)
                | Q(page__title__icontains=search)
            )
        queryset = queryset.exclude(risk_level='forbidden')
        if not include_ignored:
            queryset = [element for element in queryset if not _is_page_element_ignored(element)]
        page = None if legacy_page_filter else self.paginate_queryset(queryset)
        if page is not None:
            serializer = AppPageElementSerializer(page, many=True, context={'request': request})
            return self.get_paginated_response(serializer.data)
        serializer = AppPageElementSerializer(queryset[:100], many=True, context={'request': request})
        return Response({'success': True, 'data': serializer.data})

    @action(detail=False, methods=['get'], url_path='transitions')
    def transitions(self, request):
        queryset = (
            AppPageTransition.objects
            .select_related('from_page', 'to_page', 'trigger_element')
            .order_by('-confidence', '-updated_at')
        )
        project_id = request.query_params.get('project')
        app_package_id = request.query_params.get('app_package')
        legacy_page_filter = bool(
            request.query_params.get('page')
            and not request.query_params.get('page_id')
            and not request.query_params.get('node_id')
        )
        page_id = request.query_params.get('page_id') or request.query_params.get('node_id') or request.query_params.get('page')
        search = str(request.query_params.get('search') or '').strip()
        if project_id:
            queryset = queryset.filter(project_id=project_id)
        if app_package_id:
            queryset = queryset.filter(app_package_id=app_package_id)
        if page_id:
            queryset = queryset.filter(Q(from_page_id=page_id) | Q(to_page_id=page_id))
        if search:
            queryset = queryset.filter(
                Q(trigger_text__icontains=search)
                | Q(trigger_resource_id__icontains=search)
                | Q(from_page__business_name__icontains=search)
                | Q(to_page__business_name__icontains=search)
                | Q(from_page__title__icontains=search)
                | Q(to_page__title__icontains=search)
                | Q(from_page__activity__icontains=search)
                | Q(to_page__activity__icontains=search)
            )
        page = None if legacy_page_filter else self.paginate_queryset(queryset)
        if page is not None:
            serializer = AppPageTransitionSerializer(page, many=True, context={'request': request})
            return self.get_paginated_response(serializer.data)
        serializer = AppPageTransitionSerializer(queryset[:100], many=True, context={'request': request})
        return Response({'success': True, 'data': serializer.data})

    @action(detail=False, methods=['post'], url_path='promote-element')
    def promote_element(self, request):
        """Promote a page-map control snapshot into a pending semantic_v2 selector element."""
        element_id = request.data.get('element_id')
        page_element = (
            AppPageElement.objects
            .select_related('page', 'page__project', 'page__app_package')
            .filter(id=element_id)
            .first()
        )
        if not page_element:
            return Response({'success': False, 'message': '未找到页面地图控件候选'}, status=404)
        if page_element.risk_level == 'forbidden':
            return Response({'success': False, 'message': '该控件命中高风险策略，不允许直接入库'}, status=400)

        element, created = _promote_page_element(page_element, request.user, request.data)
        return Response({
            'success': True,
            'message': '已加入 semantic_v2 语义库，状态为待验证' if created else '已更新语义库候选元素',
            'data': AppElementSerializer(element, context={'request': request}).data,
        })

    @action(detail=False, methods=['post'], url_path='bulk-promote-elements')
    def bulk_promote_elements(self, request):
        """Promote selected page-map controls in one batch."""
        element_ids = request.data.get('element_ids') or []
        if not isinstance(element_ids, list) or not element_ids:
            return Response({'success': False, 'message': '请选择要入库的控件候选'}, status=400)

        page_elements = (
            AppPageElement.objects
            .select_related('page', 'page__project', 'page__app_package')
            .filter(id__in=element_ids)
            .exclude(risk_level='forbidden')
        )
        created = []
        updated = []
        for page_element in page_elements:
            element, is_created = _promote_page_element(page_element, request.user, request.data)
            serialized = AppElementSerializer(element, context={'request': request}).data
            if is_created:
                created.append(serialized)
            else:
                updated.append(serialized)

        skipped_count = len(set(element_ids)) - len(created) - len(updated)
        return Response({
            'success': True,
            'message': f'批量入库完成，新增 {len(created)} 个，更新 {len(updated)} 个，跳过 {skipped_count} 个',
            'data': {
                'created': created,
                'updated': updated,
                'skipped_count': skipped_count,
            },
        })

    @action(detail=False, methods=['post'], url_path='govern-elements')
    def govern_elements(self, request):
        """Mark page-map control candidates as ignored or restore them."""
        element_ids = request.data.get('element_ids') or []
        status_value = str(request.data.get('governance_status') or '').strip()
        if not isinstance(element_ids, list) or not element_ids:
            return Response({'success': False, 'message': '请选择要治理的控件候选'}, status=400)
        if status_value not in {'ignored', 'active'}:
            return Response({'success': False, 'message': 'governance_status 只能是 ignored 或 active'}, status=400)

        elements = AppPageElement.objects.filter(id__in=element_ids).exclude(risk_level='forbidden')
        updated_count = 0
        for element in elements:
            raw = dict(element.raw or {})
            if status_value == 'ignored':
                raw['governance_status'] = 'ignored'
                raw['governance_reason'] = str(request.data.get('reason') or '人工标记无需维护').strip()[:255]
            else:
                raw.pop('governance_status', None)
                raw.pop('governance_reason', None)
            element.raw = raw
            element.save(update_fields=['raw', 'updated_at'])
            updated_count += 1

        return Response({
            'success': True,
            'message': '控件候选已标记为无需维护' if status_value == 'ignored' else '控件候选已恢复',
            'data': {
                'updated_count': updated_count,
                'governance_status': status_value,
            },
        })

    @action(detail=True, methods=['post'], url_path='set-business-name')
    def set_business_name(self, request, pk=None):
        """Persist a human-confirmed business page name for reuse."""
        page = AppPageNode.objects.filter(pk=pk).first()
        if not page:
            return Response({
                'success': False,
                'stale': True,
                'message': '当前页面已被合并或删除，请刷新页面地图后重新选择页面',
            }, status=409)
        business_name = str(request.data.get('business_name') or '').strip()
        if not business_name:
            return Response({'success': False, 'message': '页面名称不能为空'}, status=400)
        page.business_name = business_name[:255]
        page.save(update_fields=['business_name', 'updated_at'])
        return Response({
            'success': True,
            'message': '页面名称已保存，后续候选控件会复用该名称',
            'data': AppPageNodeSerializer(page, context={'request': request}).data,
        })

    @action(detail=True, methods=['get'], url_path='duplicate-candidates')
    def duplicate_candidates(self, request, pk=None):
        """Recommend likely duplicated page nodes for manual merge review."""
        target_page = AppPageNode.objects.filter(pk=pk).first()
        if not target_page:
            return Response({
                'success': True,
                'message': '当前页面已被合并或删除，请刷新页面地图后继续操作',
                'data': [],
            })
        try:
            min_score = int(request.query_params.get('min_score') or 35)
        except (TypeError, ValueError):
            min_score = 35
        try:
            limit = int(request.query_params.get('limit') or 20)
        except (TypeError, ValueError):
            limit = 20
        limit = max(1, min(limit, 50))

        target_tokens = _page_element_tokens(target_page)
        queryset = (
            AppPageNode.objects
            .filter(
                project_id=target_page.project_id,
                app_package_id=target_page.app_package_id,
                platform=target_page.platform,
            )
            .exclude(id=target_page.id)
            .prefetch_related('elements')
            .order_by('-updated_at')[:200]
        )

        candidates = []
        for page in queryset:
            candidate_tokens = _page_element_tokens(page)
            score, reasons = _score_duplicate_page(target_page, target_tokens, page, candidate_tokens)
            if score < min_score:
                continue
            payload = AppPageNodeSerializer(page, context={'request': request}).data
            payload.update({
                'duplicate_score': score,
                'duplicate_reasons': reasons,
                'shared_element_count': len(target_tokens & candidate_tokens),
                'target_element_count': len(target_tokens),
                'candidate_element_count': len(candidate_tokens),
            })
            candidates.append(payload)

        candidates.sort(key=lambda item: (item['duplicate_score'], item.get('visit_count') or 0), reverse=True)
        return Response({
            'success': True,
            'data': candidates[:limit],
        })

    @action(detail=True, methods=['get'], url_path='inspection-target-draft')
    def inspection_target_draft(self, request, pk=None):
        """Build a controlled-inspection target draft from governed page-map controls."""
        page_node = AppPageNode.objects.filter(pk=pk).first()
        if not page_node:
            return Response({
                'success': True,
                'message': '当前页面已被合并或删除，请刷新页面地图后重新选择页面',
                'data': {
                    'page': None,
                    'page_name': '页面已合并或删除',
                    'target_count': 0,
                    'targets': [],
                    'target_list': [],
                    'objective': '',
                    'start_note': '请刷新页面地图后重新选择页面。',
                },
            })
        try:
            limit = int(request.query_params.get('limit') or 30)
        except (TypeError, ValueError):
            limit = 30
        limit = max(1, min(limit, 80))

        queryset = (
            page_node.elements
            .filter(enabled=True)
            .exclude(risk_level__in=['forbidden', 'high'])
            .order_by('-clickable', '-seen_count', 'role', 'id')
        )

        targets = []
        seen_names = set()
        for element in queryset[:200]:
            if _is_page_element_ignored(element):
                continue
            serializer = AppPageElementSerializer(element, context={'request': request})
            data = serializer.data
            level = data.get('candidate_level')
            if level in {'ignored', 'not_recommended'}:
                continue
            if not element.clickable and element.role not in {'button', 'switch', 'tab', 'clickable'}:
                continue
            target_name = str(data.get('candidate_name') or '').strip()
            if not target_name or target_name in {'通用容器', '未命名控件'}:
                continue
            if target_name in seen_names:
                continue
            seen_names.add(target_name)
            targets.append({
                'target_name': target_name,
                'action_type': 'tap',
                'element_id': element.id,
                'role': element.role,
                'candidate_level': level,
                'candidate_score': data.get('candidate_score'),
                'candidate_reason': data.get('candidate_reason'),
                'resource_id': element.resource_id,
                'text': element.text,
                'content_desc': element.content_desc,
                'bounds': element.bounds,
            })
            if len(targets) >= limit:
                break

        page_name = page_node.business_name or f'未命名页面 #{page_node.id}'
        return Response({
            'success': True,
            'data': {
                'page': AppPageNodeSerializer(page_node, context={'request': request}).data,
                'page_name': page_name,
                'target_count': len(targets),
                'targets': targets,
                'target_list': [item['target_name'] for item in targets],
                'objective': f'{page_name} 目标巡检：按页面地图已治理入口清单逐项验证，不点击清单外控件。',
                'start_note': f'请先让手机停留在「{page_name}」；后续可补充起始导航自动进入该页面。',
            },
        })

    @action(detail=True, methods=['post'], url_path='merge-pages')
    def merge_pages(self, request, pk=None):
        """Merge duplicated page-map nodes into the current page."""
        target_page = AppPageNode.objects.filter(pk=pk).first()
        if not target_page:
            return Response({
                'success': False,
                'stale': True,
                'message': '当前页面已被合并或删除，请刷新页面地图后重新选择页面',
            }, status=409)
        raw_page_ids = request.data.get('page_ids') or []
        if not isinstance(raw_page_ids, list):
            return Response({'success': False, 'message': 'page_ids 必须是数组'}, status=400)

        page_ids = set()
        for item in raw_page_ids:
            try:
                page_id = int(item)
            except (TypeError, ValueError):
                continue
            if page_id != target_page.id:
                page_ids.add(page_id)

        if not page_ids:
            return Response({'success': False, 'message': '请选择要合并的页面'}, status=400)

        source_page_ids = list(
            AppPageNode.objects
            .filter(
                id__in=page_ids,
                project_id=target_page.project_id,
                app_package_id=target_page.app_package_id,
                platform=target_page.platform,
            )
            .values_list('id', flat=True)
        )
        if not source_page_ids:
            return Response({'success': False, 'message': '未找到可合并页面，请确认是否属于同一项目/应用/平台'}, status=400)

        business_name = str(request.data.get('business_name') or '').strip()
        merged_count = 0
        moved_element_count = 0
        deduped_element_count = 0
        moved_transition_count = 0
        deduped_transition_count = 0

        with transaction.atomic():
            target_page = AppPageNode.objects.select_for_update().get(pk=target_page.pk)
            source_pages = list(
                AppPageNode.objects
                .select_for_update()
                .filter(id__in=source_page_ids)
            )
            if business_name:
                target_page.business_name = business_name[:255]
            elif not target_page.business_name:
                for source_page in source_pages:
                    if source_page.business_name:
                        target_page.business_name = source_page.business_name
                        break

            for source_page in source_pages:
                for element in list(source_page.elements.select_for_update()):
                    existing = AppPageElement.objects.filter(
                        page=target_page,
                        element_signature=element.element_signature,
                    ).first()
                    if existing:
                        AppPageTransition.objects.filter(trigger_element=element).update(trigger_element=existing)
                        existing.seen_count = max(existing.seen_count or 0, 0) + max(element.seen_count or 0, 0)
                        existing.enabled = existing.enabled or element.enabled
                        if not existing.semantic_element_id and element.semantic_element_id:
                            existing.semantic_element = element.semantic_element
                        if element.last_seen_run_id:
                            existing.last_seen_run = element.last_seen_run
                        existing.save(update_fields=['seen_count', 'enabled', 'semantic_element', 'last_seen_run', 'updated_at'])
                        element.delete()
                        deduped_element_count += 1
                    else:
                        element.page = target_page
                        element.save(update_fields=['page', 'updated_at'])
                        moved_element_count += 1

                transitions = list(
                    AppPageTransition.objects
                    .select_for_update()
                    .filter(Q(from_page=source_page) | Q(to_page=source_page))
                )
                for transition in transitions:
                    new_from = target_page if transition.from_page_id == source_page.id else transition.from_page
                    new_to = target_page if transition.to_page_id == source_page.id else transition.to_page
                    if new_from.id == new_to.id:
                        transition.delete()
                        deduped_transition_count += 1
                        continue

                    existing = AppPageTransition.objects.filter(
                        from_page=new_from,
                        to_page=new_to,
                        action_type=transition.action_type,
                        trigger_text=transition.trigger_text,
                        trigger_resource_id=transition.trigger_resource_id,
                        trigger_bounds=transition.trigger_bounds,
                    ).exclude(id=transition.id).first()
                    if existing:
                        existing.success_count = max(existing.success_count or 0, 0) + max(transition.success_count or 0, 0)
                        existing.failure_count = max(existing.failure_count or 0, 0) + max(transition.failure_count or 0, 0)
                        existing.confidence = max(existing.confidence or 0, transition.confidence or 0)
                        if not existing.trigger_element_id and transition.trigger_element_id:
                            existing.trigger_element = transition.trigger_element
                        if transition.last_seen_run_id:
                            existing.last_seen_run = transition.last_seen_run
                        existing.save(update_fields=[
                            'success_count',
                            'failure_count',
                            'confidence',
                            'trigger_element',
                            'last_seen_run',
                            'updated_at',
                        ])
                        transition.delete()
                        deduped_transition_count += 1
                    else:
                        transition.from_page = new_from
                        transition.to_page = new_to
                        transition.save(update_fields=['from_page', 'to_page', 'updated_at'])
                        moved_transition_count += 1

                target_page.visit_count = max(target_page.visit_count or 0, 0) + max(source_page.visit_count or 0, 0)
                if not target_page.representative_screenshot and source_page.representative_screenshot:
                    target_page.representative_screenshot = source_page.representative_screenshot
                if not target_page.semantic_signature and source_page.semantic_signature:
                    target_page.semantic_signature = source_page.semantic_signature
                if source_page.last_seen_run_id:
                    target_page.last_seen_run = source_page.last_seen_run
                source_page.delete()
                merged_count += 1

            target_page.save(update_fields=[
                'business_name',
                'visit_count',
                'representative_screenshot',
                'semantic_signature',
                'last_seen_run',
                'updated_at',
            ])

        return Response({
            'success': True,
            'message': f'页面合并完成：合并 {merged_count} 个页面，迁移控件 {moved_element_count} 个，去重控件 {deduped_element_count} 个',
            'data': {
                'target_page': AppPageNodeSerializer(target_page, context={'request': request}).data,
                'merged_count': merged_count,
                'moved_element_count': moved_element_count,
                'deduped_element_count': deduped_element_count,
                'moved_transition_count': moved_transition_count,
                'deduped_transition_count': deduped_transition_count,
            },
        })


def _promote_page_element(page_element, user, payload):
    description = str(payload.get('description') or '').strip()
    semantic_page = str(payload.get('semantic_page') or page_element.page.business_name or '').strip()
    semantic_role = str(payload.get('semantic_role') or page_element.role or 'control').strip()
    semantic_object = str(
        payload.get('semantic_object')
        or page_element.text
        or page_element.content_desc
        or _build_page_element_candidate_name(page_element)
        or _resource_tail(page_element.resource_id)
        or semantic_role
    ).strip()
    locator_key = str(payload.get('locator_key') or '').strip() or _build_locator_key(page_element, semantic_role)
    element_name = _unique_element_name(f'semantic_v2.{locator_key}')
    display_name = description or semantic_object or locator_key

    existing = AppElement.objects.filter(config__page_map_element_id=page_element.id, is_active=True).first()
    config = {
        'strategy': 'page_map_selector',
        'semantic_version': 'v2',
        'semantic_status': '待验证',
        'semantic_status_source': 'page_map_candidate',
        'needs_human_confirm': True,
        'description': display_name,
        'manual_note': str(payload.get('manual_note') or '由页面地图控件候选生成，首次用于用例前建议人工验证业务语义和定位稳定性。').strip(),
        'package': page_element.page.app_identifier,
        'activity': page_element.page.activity,
        'resource_id': page_element.resource_id,
        'class': page_element.class_name,
        'text': page_element.text,
        'content_desc': page_element.content_desc,
        'bounds': page_element.bounds,
        'normalized_bounds': page_element.normalized_bounds,
        'locator_key': locator_key,
        'semantic_page': semantic_page,
        'semantic_object': semantic_object,
        'semantic_role': semantic_role,
        'interaction_role': semantic_role,
        'page_map_element_id': page_element.id,
        'page_map_node_id': page_element.page_id,
        'page_signature': page_element.page.page_signature,
        'source_confidence': 'medium',
        'source': 'page_map_candidate',
    }
    tags = ['semantic_v2', '页面地图候选', '待验证', semantic_role]

    if existing:
        existing.config = {**(existing.config or {}), **config}
        existing.tags = sorted(set(list(existing.tags or []) + tags))
        existing.project = page_element.page.project or existing.project
        existing.element_type = 'selector'
        existing.save(update_fields=['config', 'tags', 'project', 'element_type', 'updated_at'])
        page_element.semantic_element = existing
        page_element.save(update_fields=['semantic_element', 'updated_at'])
        return existing, False

    created = AppElement.objects.create(
        project=page_element.page.project,
        name=element_name,
        element_type='selector',
        tags=tags,
        config=config,
        created_by=user,
    )
    page_element.semantic_element = created
    page_element.save(update_fields=['semantic_element', 'updated_at'])
    return created, True


def _resource_tail(resource_id):
    text = str(resource_id or '').strip()
    return text.rsplit('/', 1)[-1] if text else ''


def _page_element_tokens(page):
    tokens = set()
    elements = getattr(page, '_prefetched_objects_cache', {}).get('elements')
    if elements is None:
        elements = page.elements.filter(enabled=True)[:120]
    for element in elements:
        for value in (element.resource_id, element.text, element.content_desc):
            token = _normalize_page_token(value)
            if token:
                tokens.add(token)
        tail = _normalize_page_token(_resource_tail(element.resource_id))
        if tail:
            tokens.add(tail)
    return tokens


def _normalize_page_token(value):
    text = str(value or '').strip().lower()
    if not text:
        return ''
    text = text.rsplit('/', 1)[-1]
    text = re.sub(r'\s+', '', text)
    return text[:120]


def _score_duplicate_page(target_page, target_tokens, candidate_page, candidate_tokens):
    score = 0
    reasons = []

    target_name = str(target_page.business_name or '').strip()
    candidate_name = str(candidate_page.business_name or '').strip()
    if target_name and candidate_name and target_name == candidate_name:
        score += 30
        reasons.append('页面业务名一致')

    if target_page.semantic_signature and target_page.semantic_signature == candidate_page.semantic_signature:
        score += 35
        reasons.append('语义签名一致')

    if target_page.activity and target_page.activity == candidate_page.activity:
        score += 20
        reasons.append('Activity 一致')

    if target_page.screen_size and target_page.screen_size == candidate_page.screen_size:
        score += 5
        reasons.append('屏幕尺寸一致')

    union_count = len(target_tokens | candidate_tokens)
    shared_count = len(target_tokens & candidate_tokens)
    if union_count:
        overlap_score = round((shared_count / union_count) * 40)
        if overlap_score:
            score += overlap_score
            reasons.append(f'控件特征重叠 {shared_count}/{union_count}')

    if target_page.activity and target_page.activity != candidate_page.activity and score < 70:
        score = max(0, score - 15)
        reasons.append('Activity 不同，已降权')

    return min(score, 100), reasons


def _build_locator_key(page_element, role):
    raw = page_element.resource_id or page_element.text or page_element.content_desc or f'element_{page_element.id}'
    tail = _resource_tail(raw) or raw
    key = re.sub(r'[^0-9a-zA-Z_]+', '_', str(tail).strip()).strip('_').lower()
    role_prefix = re.sub(r'[^0-9a-zA-Z_]+', '_', str(role or 'control')).strip('_').lower()
    if not key:
        key = f'element_{page_element.id}'
    if role_prefix and not key.startswith(f'{role_prefix}_'):
        key = f'{role_prefix}_{key}'
    return key[:80]


def _unique_element_name(base_name):
    base = re.sub(r'\.+', '.', str(base_name or 'semantic_v2.element').strip('.'))[:180]
    if not AppElement.objects.filter(name=base).exists():
        return base
    index = 2
    while True:
        candidate = f'{base}.{index}'
        if not AppElement.objects.filter(name=candidate).exists():
            return candidate
        index += 1
