# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appelement',
            name='element_type',
            field=models.CharField(choices=[('image', '图片元素'), ('pos', '坐标元素'), ('region', '区域元素'), ('selector', '定位元素')], max_length=10, verbose_name='元素类型'),
        ),
    ]
