# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0003_selector_element_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptestexecution',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='APP性能指标'),
        ),
    ]
