# Generated by Codex on 2026-07-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0004_app_test_execution_performance_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='appproject',
            name='app_package',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='projects',
                to='app_automation.apppackage',
                verbose_name='默认应用包',
            ),
        ),
    ]
