# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0005_app_project_app_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appproject',
            old_name='app_package',
            new_name='android_app_package',
        ),
        migrations.AlterField(
            model_name='appproject',
            name='android_app_package',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='android_projects',
                to='app_automation.apppackage',
                verbose_name='Android默认应用包',
            ),
        ),
        migrations.AddField(
            model_name='appproject',
            name='ios_bundle_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='iOS Bundle ID'),
        ),
    ]
