# Generated by Codex on 2026-07-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


DEFAULT_SEMANTIC_DICTIONARY = {
    'page': ['登录页', '验证码登录页', '创建社区页', '社区详情页', '关注列表页', '个人中心页', '设置页', '公共弹窗', '公共顶部栏', '公共Toast'],
    'object': ['手机号', '验证码', '登录', '退出登录', '取消', '确认', '返回', '社区名称', '社区介绍', '创建社区', '关注社区', '关注列表', '社区头像', '个人头像', '昵称', '搜索', '设置'],
    'role': ['按钮', '输入框', '文本', '列表项', '图片', '开关', '勾选框', '弹窗', 'Tab', 'Toast', '容器'],
    'purpose': ['点击', '输入', '展示', '断言', '选择', '返回', '确认', '取消'],
}


def seed_semantic_dictionary(apps, schema_editor):
    AppSemanticDictionary = apps.get_model('app_automation', 'AppSemanticDictionary')
    for category, values in DEFAULT_SEMANTIC_DICTIONARY.items():
        for index, value in enumerate(values, start=1):
            AppSemanticDictionary.objects.get_or_create(
                project=None,
                category=category,
                value=value,
                defaults={
                    'label': value,
                    'sort_order': index * 10,
                    'is_active': True,
                },
            )


def unseed_semantic_dictionary(apps, schema_editor):
    AppSemanticDictionary = apps.get_model('app_automation', 'AppSemanticDictionary')
    for category, values in DEFAULT_SEMANTIC_DICTIONARY.items():
        AppSemanticDictionary.objects.filter(project=None, category=category, value__in=values).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_automation', '0006_project_platform_app_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSemanticDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('page', 'Page'), ('object', 'Business Object'), ('role', 'Control Role'), ('purpose', 'Purpose')], max_length=32, verbose_name='Category')),
                ('value', models.CharField(max_length=120, verbose_name='Value')),
                ('label', models.CharField(blank=True, default='', max_length=120, verbose_name='Label')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_semantic_dictionaries', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_dictionaries', to='app_automation.appproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'APP semantic dictionary',
                'verbose_name_plural': 'APP semantic dictionaries',
                'db_table': 'app_semantic_dictionaries',
                'ordering': ['category', 'sort_order', 'value'],
            },
        ),
        migrations.AddIndex(
            model_name='appsemanticdictionary',
            index=models.Index(fields=['category', 'is_active'], name='app_semanti_categor_25937b_idx'),
        ),
        migrations.AddIndex(
            model_name='appsemanticdictionary',
            index=models.Index(fields=['project', 'category'], name='app_semanti_project_dc6fd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='appsemanticdictionary',
            constraint=models.UniqueConstraint(fields=('project', 'category', 'value'), name='uniq_app_semantic_dict_project_category_value'),
        ),
        migrations.RunPython(seed_semantic_dictionary, unseed_semantic_dictionary),
    ]
