# Generated by Codex on 2026-07-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0007_app_semantic_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsemanticdictionary',
            name='governance_status',
            field=models.CharField(
                choices=[
                    ('approved', 'Approved'),
                    ('pending', 'Pending review'),
                    ('merged', 'Merged'),
                    ('deprecated', 'Deprecated'),
                ],
                default='approved',
                max_length=20,
                verbose_name='Governance status',
            ),
        ),
        migrations.AddField(
            model_name='appsemanticdictionary',
            name='merged_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='merged_items',
                to='app_automation.appsemanticdictionary',
                verbose_name='Merged to',
            ),
        ),
        migrations.AddField(
            model_name='appsemanticdictionary',
            name='source',
            field=models.CharField(blank=True, default='manual', max_length=40, verbose_name='Source'),
        ),
        migrations.AddIndex(
            model_name='appsemanticdictionary',
            index=models.Index(fields=['governance_status', 'category'], name='app_semanti_governa_0525d6_idx'),
        ),
    ]
