# Generated by Django 4.2.7 on 2026-07-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_automation', '0008_semantic_dictionary_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppExplorationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Task name')),
                ('objective', models.TextField(blank=True, default='', verbose_name='Objective')),
                ('start_note', models.TextField(blank=True, default='', verbose_name='Start note')),
                ('max_steps', models.IntegerField(default=20, verbose_name='Max steps')),
                ('max_duration', models.IntegerField(default=300, verbose_name='Max duration seconds')),
                ('blacklist_keywords', models.JSONField(blank=True, default=list, verbose_name='Blacklist keywords')),
                ('strategy', models.CharField(default='rule_mvp', max_length=50, verbose_name='Strategy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('stopped', 'Stopped')], default='pending', max_length=20, verbose_name='Status')),
                ('result', models.CharField(blank=True, choices=[('passed', 'No issue found'), ('warning', 'Issues found'), ('failed', 'Execution failed')], default=None, max_length=20, null=True, verbose_name='Result')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery task ID')),
                ('progress', models.IntegerField(default=0, verbose_name='Progress')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('duration', models.FloatField(default=0, verbose_name='Duration seconds')),
                ('total_steps', models.IntegerField(default=0, verbose_name='Total steps')),
                ('explored_pages', models.IntegerField(default=0, verbose_name='Explored pages')),
                ('issue_count', models.IntegerField(default=0, verbose_name='Issue count')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Summary')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('app_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exploration_tasks', to='app_automation.apppackage', verbose_name='App package')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_exploration_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exploration_tasks', to='app_automation.appdevice', verbose_name='Device')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exploration_tasks', to='app_automation.appproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'APP exploration task',
                'verbose_name_plural': 'APP exploration tasks',
                'db_table': 'app_exploration_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppExplorationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(verbose_name='Step index')),
                ('action_type', models.CharField(choices=[('tap', 'Tap'), ('swipe', 'Swipe'), ('back', 'Back'), ('wait', 'Wait'), ('stop', 'Stop')], max_length=20, verbose_name='Action type')),
                ('action_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Action label')),
                ('target_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Target text')),
                ('target_resource_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Target resource id')),
                ('target_class', models.CharField(blank=True, default='', max_length=255, verbose_name='Target class')),
                ('bounds', models.CharField(blank=True, default='', max_length=100, verbose_name='Bounds')),
                ('x', models.IntegerField(blank=True, null=True, verbose_name='X')),
                ('y', models.IntegerField(blank=True, null=True, verbose_name='Y')),
                ('before_activity', models.CharField(blank=True, default='', max_length=255, verbose_name='Before activity')),
                ('after_activity', models.CharField(blank=True, default='', max_length=255, verbose_name='After activity')),
                ('before_signature', models.CharField(blank=True, default='', max_length=64, verbose_name='Before signature')),
                ('after_signature', models.CharField(blank=True, default='', max_length=64, verbose_name='After signature')),
                ('changed', models.BooleanField(default=False, verbose_name='Page changed')),
                ('before_screenshot', models.CharField(blank=True, default='', max_length=500, verbose_name='Before screenshot')),
                ('after_screenshot', models.CharField(blank=True, default='', max_length=500, verbose_name='After screenshot')),
                ('page_source_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Page source path')),
                ('issue_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Issue type')),
                ('issue_message', models.TextField(blank=True, default='', verbose_name='Issue message')),
                ('logcat_excerpt', models.TextField(blank=True, default='', verbose_name='Logcat excerpt')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Raw data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app_automation.appexplorationtask', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'APP exploration step',
                'verbose_name_plural': 'APP exploration steps',
                'db_table': 'app_exploration_steps',
                'ordering': ['task_id', 'step_index'],
            },
        ),
        migrations.AddIndex(
            model_name='appexplorationtask',
            index=models.Index(fields=['status'], name='app_explora_status_0b51cc_idx'),
        ),
        migrations.AddIndex(
            model_name='appexplorationtask',
            index=models.Index(fields=['-created_at'], name='app_explora_created_9de2da_idx'),
        ),
        migrations.AddIndex(
            model_name='appexplorationtask',
            index=models.Index(fields=['project'], name='app_explora_project_4c0a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='appexplorationstep',
            index=models.Index(fields=['task', 'step_index'], name='app_explora_task_id_efe7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='appexplorationstep',
            index=models.Index(fields=['issue_type'], name='app_explora_issue_t_868e8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appexplorationstep',
            unique_together={('task', 'step_index')},
        ),
    ]
