# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0009_app_exploration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appexplorationtask',
            name='start_actions',
            field=models.JSONField(blank=True, default=list, verbose_name='Start navigation actions'),
        ),
    ]
