# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0010_app_exploration_start_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='appexplorationtask',
            name='entry_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='Entry keywords'),
        ),
    ]
