# Generated by Django 4.2.7 on 2026-07-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0011_app_exploration_entry_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='appexplorationtask',
            name='source_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='Source summary'),
        ),
        migrations.AddField(
            model_name='appexplorationtask',
            name='source_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_tasks', to='app_automation.appexplorationtask', verbose_name='Source exploration task'),
        ),
        migrations.AddField(
            model_name='appexplorationtask',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Source type'),
        ),
    ]
