# Generated by Django 4.2.7 on 2026-07-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0013_exploration_runs_and_target_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='android', max_length=20, verbose_name='Platform')),
                ('app_identifier', models.CharField(blank=True, default='', max_length=255, verbose_name='App identifier')),
                ('app_version', models.CharField(blank=True, default='', max_length=100, verbose_name='App version')),
                ('activity', models.CharField(blank=True, default='', max_length=255, verbose_name='Activity')),
                ('page_signature', models.CharField(max_length=64, verbose_name='Page signature')),
                ('semantic_signature', models.CharField(blank=True, default='', max_length=64, verbose_name='Semantic signature')),
                ('business_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Business page name')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Page title')),
                ('representative_screenshot', models.CharField(blank=True, default='', max_length=500, verbose_name='Representative screenshot')),
                ('screen_size', models.JSONField(blank=True, default=list, verbose_name='Screen size')),
                ('visit_count', models.IntegerField(default=0, verbose_name='Visit count')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Raw page data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('app_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_nodes', to='app_automation.apppackage', verbose_name='App package')),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_page_nodes', to='app_automation.appexplorationrun', verbose_name='First seen run')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_page_nodes', to='app_automation.appexplorationrun', verbose_name='Last seen run')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_nodes', to='app_automation.appproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'APP page node',
                'verbose_name_plural': 'APP page nodes',
                'db_table': 'app_page_nodes',
            },
        ),
        migrations.AlterField(
            model_name='appelement',
            name='config',
            field=models.JSONField(default=dict, help_text='\n        image类型: {\n            "image_category": "common",\n            "image_path": "common/login.png", \n            "file_hash": "abc123...",\n            "image_threshold": 0.7, \n            "rgb": false\n        }\n        pos类型: {"x": 100, "y": 200}\n        region类型: {"x1": 100, "y1": 200, "x2": 300, "y2": 400}\n        selector类型: {\n            "package": "com.example.demo",\n            "activity": "com.example.demo.activity.LoginActivity",\n            "resource_id": "com.example.demo:id/btnLogin",\n            "class": "android.widget.Button",\n            "text": "登录",\n            "content_desc": "",\n            "hint": "",\n            "clickable": true,\n            "focusable": true,\n            "enabled": true,\n            "bounds": "[96,984][984,1128]",\n            "locator_key": "btn_login",\n            "source_file": "demo_login.yaml"\n        }\n        ', verbose_name='元素配置'),
        ),
        migrations.CreateModel(
            name='AppPageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_signature', models.CharField(max_length=64, verbose_name='Element signature')),
                ('text', models.CharField(blank=True, default='', max_length=255, verbose_name='Text')),
                ('content_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='Content desc')),
                ('resource_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Resource id')),
                ('class_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Class name')),
                ('role', models.CharField(blank=True, default='', max_length=80, verbose_name='Control role')),
                ('bounds', models.CharField(blank=True, default='', max_length=100, verbose_name='Bounds')),
                ('normalized_bounds', models.JSONField(blank=True, default=dict, verbose_name='Normalized bounds')),
                ('clickable', models.BooleanField(default=False, verbose_name='Clickable')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('risk_level', models.CharField(blank=True, default='', max_length=30, verbose_name='Risk level')),
                ('seen_count', models.IntegerField(default=0, verbose_name='Seen count')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Raw element data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_page_elements', to='app_automation.appexplorationrun', verbose_name='First seen run')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_page_elements', to='app_automation.appexplorationrun', verbose_name='Last seen run')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='app_automation.apppagenode', verbose_name='Page node')),
                ('semantic_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_element_snapshots', to='app_automation.appelement', verbose_name='Linked semantic element')),
            ],
            options={
                'verbose_name': 'APP page element',
                'verbose_name_plural': 'APP page elements',
                'db_table': 'app_page_elements',
            },
        ),
        migrations.CreateModel(
            name='AppPageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(default='tap', max_length=30, verbose_name='Action type')),
                ('trigger_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Trigger text')),
                ('trigger_resource_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Trigger resource id')),
                ('trigger_bounds', models.CharField(blank=True, default='', max_length=100, verbose_name='Trigger bounds')),
                ('success_count', models.IntegerField(default=0, verbose_name='Success count')),
                ('failure_count', models.IntegerField(default=0, verbose_name='Failure count')),
                ('confidence', models.FloatField(default=0, verbose_name='Confidence')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Raw transition data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('app_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_transitions', to='app_automation.apppackage', verbose_name='App package')),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='app_automation.apppagenode', verbose_name='From page')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_page_transitions', to='app_automation.appexplorationrun', verbose_name='Last seen run')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_transitions', to='app_automation.appproject', verbose_name='Project')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='app_automation.apppagenode', verbose_name='To page')),
                ('trigger_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_transitions', to='app_automation.apppageelement', verbose_name='Trigger element')),
            ],
            options={
                'verbose_name': 'APP page transition',
                'verbose_name_plural': 'APP page transitions',
                'db_table': 'app_page_transitions',
                'indexes': [models.Index(fields=['project', 'app_package'], name='app_page_tr_project_f3200e_idx'), models.Index(fields=['from_page', 'to_page'], name='app_page_tr_from_pa_f5cd12_idx'), models.Index(fields=['confidence'], name='app_page_tr_confide_0403a3_idx')],
                'unique_together': {('from_page', 'to_page', 'action_type', 'trigger_text', 'trigger_resource_id', 'trigger_bounds')},
            },
        ),
        migrations.AddIndex(
            model_name='apppagenode',
            index=models.Index(fields=['project', 'app_package', 'platform'], name='app_page_no_project_3a7156_idx'),
        ),
        migrations.AddIndex(
            model_name='apppagenode',
            index=models.Index(fields=['page_signature'], name='app_page_no_page_si_9d7b08_idx'),
        ),
        migrations.AddIndex(
            model_name='apppagenode',
            index=models.Index(fields=['semantic_signature'], name='app_page_no_semanti_d5175c_idx'),
        ),
        migrations.AddIndex(
            model_name='apppagenode',
            index=models.Index(fields=['activity'], name='app_page_no_activit_1b5606_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apppagenode',
            unique_together={('project', 'app_package', 'platform', 'page_signature')},
        ),
        migrations.AddIndex(
            model_name='apppageelement',
            index=models.Index(fields=['page', 'role'], name='app_page_el_page_id_b2febd_idx'),
        ),
        migrations.AddIndex(
            model_name='apppageelement',
            index=models.Index(fields=['resource_id'], name='app_page_el_resourc_d1fff0_idx'),
        ),
        migrations.AddIndex(
            model_name='apppageelement',
            index=models.Index(fields=['text'], name='app_page_el_text_d7b32b_idx'),
        ),
        migrations.AddIndex(
            model_name='apppageelement',
            index=models.Index(fields=['risk_level'], name='app_page_el_risk_le_395648_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apppageelement',
            unique_together={('page', 'element_signature')},
        ),
    ]
