# Generated by Codex on 2026-07-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_automation', '0014_apppagenode_alter_appelement_config_apppageelement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinspectiontargetresult',
            name='review_context',
            field=models.JSONField(blank=True, default=dict, verbose_name='Review context'),
        ),
        migrations.AddField(
            model_name='appinspectiontargetresult',
            name='review_note',
            field=models.TextField(blank=True, default='', verbose_name='Review note'),
        ),
        migrations.AddField(
            model_name='appinspectiontargetresult',
            name='review_resolution',
            field=models.CharField(blank=True, choices=[('valid_issue', 'Valid issue'), ('normal_behavior', 'Normal behavior'), ('element_needs_update', 'Element needs update'), ('target_should_remove', 'Target should remove'), ('wrong_start_page', 'Wrong start page'), ('rule_exception', 'Rule exception')], default='', max_length=40, verbose_name='Review resolution'),
        ),
        migrations.AddField(
            model_name='appinspectiontargetresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at'),
        ),
        migrations.AddField(
            model_name='appinspectiontargetresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_app_inspection_targets', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
        migrations.CreateModel(
            name='AppInspectionReviewRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=255, verbose_name='Target name')),
                ('status', models.CharField(blank=True, default='', max_length=40, verbose_name='Matched status')),
                ('resolution', models.CharField(choices=[('valid_issue', 'Valid issue'), ('normal_behavior', 'Normal behavior'), ('element_needs_update', 'Element needs update'), ('target_should_remove', 'Target should remove'), ('wrong_start_page', 'Wrong start page'), ('rule_exception', 'Rule exception')], max_length=40, verbose_name='Review resolution')),
                ('note', models.TextField(blank=True, default='', verbose_name='Review note')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_inspection_review_rules', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('created_from_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_rules', to='app_automation.appinspectiontargetresult', verbose_name='Created from target result')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_review_rules', to='app_automation.appexplorationtask', verbose_name='Exploration task')),
            ],
            options={
                'verbose_name': 'APP inspection review rule',
                'verbose_name_plural': 'APP inspection review rules',
                'db_table': 'app_inspection_review_rules',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appinspectiontargetresult',
            index=models.Index(fields=['review_resolution'], name='app_inspect_review_91d783_idx'),
        ),
        migrations.AddIndex(
            model_name='appinspectionreviewrule',
            index=models.Index(fields=['task', 'target_name'], name='app_inspect_task_id_47ff1d_idx'),
        ),
        migrations.AddIndex(
            model_name='appinspectionreviewrule',
            index=models.Index(fields=['resolution'], name='app_inspect_resolut_b2f8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='appinspectionreviewrule',
            index=models.Index(fields=['enabled'], name='app_inspect_enabled_cbe2f9_idx'),
        ),
    ]
