# Generated by Codex on 2026-07-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0015_inspection_target_review'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appinspectionreviewrule',
            new_name='app_inspect_task_id_9744ab_idx',
            old_name='app_inspect_task_id_47ff1d_idx',
        ),
        migrations.RenameIndex(
            model_name='appinspectionreviewrule',
            new_name='app_inspect_resolut_9559c2_idx',
            old_name='app_inspect_resolut_b2f8dd_idx',
        ),
        migrations.RenameIndex(
            model_name='appinspectionreviewrule',
            new_name='app_inspect_enabled_dc7c2d_idx',
            old_name='app_inspect_enabled_cbe2f9_idx',
        ),
        migrations.RenameIndex(
            model_name='appinspectiontargetresult',
            new_name='app_inspect_review__914c97_idx',
            old_name='app_inspect_review_91d783_idx',
        ),
    ]
