# Generated by Django 4.2.7 on 2026-09-01 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def initialize_case_governance(apps, schema_editor):
    AppProject = apps.get_model('app_automation', 'AppProject')
    AppTestCase = apps.get_model('app_automation', 'AppTestCase')
    AppTestCaseFolder = apps.get_model('app_automation', 'AppTestCaseFolder')
    AppTestCaseTag = apps.get_model('app_automation', 'AppTestCaseTag')

    folder_names = [
        '未分类',
        '登录',
        '底部导航',
        '社区抽屉',
        '搜索',
        '社区首页',
        '社区大厅',
        '动态',
        '插件文章',
        '语音房',
        '发布组队',
        '消息',
        '商城',
        '设置',
    ]
    tag_names = [
        '主链路',
        '阻塞发布',
        '高频执行',
        '数据依赖',
        '外部服务依赖',
        '高风险操作',
        '人工确认',
        'AI生成',
        'AI探索沉淀',
    ]
    folder_keywords = [
        ('登录', ['登录-']),
        ('底部导航', ['底部TAB']),
        ('社区抽屉', ['社区抽屉']),
        ('搜索', ['发现/搜索', '搜索社区']),
        ('社区首页', ['社区首页']),
        ('社区大厅', ['社区大厅', '全员大厅']),
        ('动态', ['动态-']),
        ('插件文章', ['插件文章']),
        ('语音房', ['语音房-']),
        ('发布组队', ['发布组队']),
        ('消息', ['消息-']),
        ('商城', ['商城-']),
        ('设置', ['设置-']),
    ]

    for project in AppProject.objects.all():
        folders = {}
        for order, name in enumerate(folder_names):
            folder, _ = AppTestCaseFolder.objects.get_or_create(
                project=project,
                parent=None,
                name=name,
                defaults={'order': order, 'level': 1, 'is_system': name == '未分类'},
            )
            folders[name] = folder

        tags = {}
        for name in tag_names:
            tag, _ = AppTestCaseTag.objects.get_or_create(project=project, name=name)
            tags[name] = tag

        for case in AppTestCase.objects.filter(project=project):
            target_folder = folders.get('未分类')
            for folder_name, keywords in folder_keywords:
                if any(keyword in case.name for keyword in keywords):
                    target_folder = folders.get(folder_name) or target_folder
                    break

            ui_flow = case.ui_flow or []
            if isinstance(ui_flow, dict):
                steps = ui_flow.get('steps') or ui_flow.get('ui_flow') or ui_flow.get('flow') or []
            elif isinstance(ui_flow, list):
                steps = ui_flow
            else:
                steps = []

            priority = 'P0' if 'APP-P0-' in case.name else 'P1'
            lifecycle_status = 'active' if steps else 'draft'
            case_type = 'smoke' if priority == 'P0' else 'regression'
            data_impact = 'readonly'
            if any(keyword in case.name for keyword in ['登录-账号密码正常登录', '关注社区', '退出或取消关注社区', '发送文本消息', '退出登录']):
                data_impact = 'self_healing'
            if any(keyword in case.name for keyword in ['退出登录']):
                data_impact = 'destructive'

            case.folder = case.folder or target_folder
            case.priority = case.priority or priority
            case.lifecycle_status = case.lifecycle_status or lifecycle_status
            case.case_type = case.case_type or case_type
            case.data_impact = case.data_impact or data_impact
            case.source = case.source or 'manual'
            case.maintainer = case.maintainer or case.created_by
            case.save(update_fields=[
                'folder',
                'priority',
                'lifecycle_status',
                'case_type',
                'data_impact',
                'source',
                'maintainer',
            ])

            if 'APP-P0-' in case.name and tags.get('主链路'):
                case.tags.add(tags['主链路'])
            if 'APP-P0-' in case.name and tags.get('高频执行'):
                case.tags.add(tags['高频执行'])
            if data_impact in {'self_healing', 'destructive'} and tags.get('数据依赖'):
                case.tags.add(tags['数据依赖'])
            if data_impact == 'destructive' and tags.get('高风险操作'):
                case.tags.add(tags['高风险操作'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_automation', '0016_normalize_inspection_review_index_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTestCaseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='目录名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='目录说明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('level', models.IntegerField(default=1, verbose_name='层级')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统目录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'APP用例业务目录',
                'verbose_name_plural': 'APP用例业务目录',
                'db_table': 'app_test_case_folders',
                'ordering': ['project_id', 'parent_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AppTestCaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='标签名称')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='标签颜色')),
                ('description', models.TextField(blank=True, default='', verbose_name='标签说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'APP用例标签',
                'verbose_name_plural': 'APP用例标签',
                'db_table': 'app_test_case_tags',
                'ordering': ['project_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='case_type',
            field=models.CharField(choices=[('smoke', '冒烟'), ('regression', '回归'), ('core', '核心链路'), ('negative', '异常场景'), ('special', '专项')], default='regression', max_length=30, verbose_name='用例类型'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='data_impact',
            field=models.CharField(choices=[('readonly', '只读'), ('mutates', '会改数据'), ('self_healing', '可闭环恢复'), ('destructive', '破坏性')], default='readonly', max_length=30, verbose_name='数据影响'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='lifecycle_status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('maintenance', '维护中'), ('deprecated', '已废弃')], default='active', max_length=30, verbose_name='生命周期'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_app_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='维护人'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='priority',
            field=models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P1', max_length=10, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='source',
            field=models.CharField(choices=[('manual', '人工创建'), ('recording', '录制生成'), ('ai_generated', 'AI生成'), ('ai_exploration', 'AI探索转化'), ('imported', '导入')], default='manual', max_length=30, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='apptestcasetag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_test_case_tags', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='apptestcasetag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_tags', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apptestcasefolder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_test_case_folders', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='apptestcasefolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_automation.apptestcasefolder', verbose_name='父目录'),
        ),
        migrations.AddField(
            model_name='apptestcasefolder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_folders', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='app_automation.apptestcasefolder', verbose_name='业务目录'),
        ),
        migrations.AddField(
            model_name='apptestcase',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='test_cases', to='app_automation.apptestcasetag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='apptestcase',
            index=models.Index(fields=['project', 'folder'], name='app_test_ca_project_a7a7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestcase',
            index=models.Index(fields=['project', 'priority'], name='app_test_ca_project_06bf54_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestcase',
            index=models.Index(fields=['project', 'lifecycle_status'], name='app_test_ca_project_6be7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestcase',
            index=models.Index(fields=['project', 'case_type'], name='app_test_ca_project_ff9a45_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestcase',
            index=models.Index(fields=['maintainer'], name='app_test_ca_maintai_7f577a_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestcasetag',
            index=models.Index(fields=['project', 'is_active'], name='app_test_ca_project_8c9fac_idx'),
        ),
        migrations.AddConstraint(
            model_name='apptestcasetag',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_app_case_tag_project_name'),
        ),
        migrations.AddIndex(
            model_name='apptestcasefolder',
            index=models.Index(fields=['project', 'parent'], name='app_test_ca_project_e9a743_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestcasefolder',
            index=models.Index(fields=['project', 'level'], name='app_test_ca_project_6ebe74_idx'),
        ),
        migrations.AddConstraint(
            model_name='apptestcasefolder',
            constraint=models.UniqueConstraint(fields=('project', 'parent', 'name'), name='uniq_app_case_folder_project_parent_name'),
        ),
        migrations.AlterField(
            model_name='apptestsuite',
            name='execution_status',
            field=models.CharField(choices=[('not_run', '未执行'), ('running', '执行中'), ('completed', '已完成'), ('error', '执行异常'), ('stopped', '已停止')], default='not_run', max_length=20, verbose_name='执行状态'),
        ),
        migrations.RunPython(initialize_case_governance, noop_reverse),
    ]
