# Generated by Django 4.2.7 on 2026-09-03 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_automation', '0017_apptestcasefolder_apptestcasetag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppExecutionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=120, unique=True, verbose_name='Agent标识')),
                ('name', models.CharField(max_length=120, verbose_name='Agent名称')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('busy', '执行中'), ('disabled', '已停用')], default='offline', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('capabilities', models.JSONField(blank=True, default=dict, verbose_name='能力信息')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后访问IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'APP执行机Agent',
                'verbose_name_plural': 'APP执行机Agent',
                'db_table': 'app_execution_agents',
                'ordering': ['-last_seen_at', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='agent_claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agent领取时间'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='agent_last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agent最近回报时间'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='agent_message',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Agent执行消息'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='agent_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Agent回传数据'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='execution_mode',
            field=models.CharField(choices=[('server', '服务器执行'), ('agent', '本地Agent执行')], default='server', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AddField(
            model_name='appexecutionagent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_execution_agents', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='app_automation.appexecutionagent', verbose_name='所属执行机'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='app_automation.appexecutionagent', verbose_name='执行Agent'),
        ),
        migrations.AddIndex(
            model_name='appdevice',
            index=models.Index(fields=['agent', 'status'], name='app_devices_agent_i_454a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestexecution',
            index=models.Index(fields=['execution_mode', 'status'], name='app_test_ex_executi_08a70e_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestexecution',
            index=models.Index(fields=['agent', 'status'], name='app_test_ex_agent_i_398088_idx'),
        ),
        migrations.AddIndex(
            model_name='appexecutionagent',
            index=models.Index(fields=['agent_id'], name='app_executi_agent_i_424a05_idx'),
        ),
        migrations.AddIndex(
            model_name='appexecutionagent',
            index=models.Index(fields=['status', 'last_seen_at'], name='app_executi_status_640e9f_idx'),
        ),
    ]
