# Generated by Django 4.2.7 on 2026-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0018_appexecutionagent_apptestexecution_agent_claimed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appexecutionagent',
            name='health_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='环境检查时间'),
        ),
        migrations.AddField(
            model_name='appexecutionagent',
            name='health_checks',
            field=models.JSONField(blank=True, default=list, verbose_name='环境检查项'),
        ),
        migrations.AddField(
            model_name='appexecutionagent',
            name='health_status',
            field=models.CharField(choices=[('unknown', '未检查'), ('ready', '可执行'), ('warning', '部分可用'), ('blocked', '不可执行')], default='unknown', max_length=20, verbose_name='环境状态'),
        ),
        migrations.AddField(
            model_name='appexecutionagent',
            name='health_summary',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='环境摘要'),
        ),
    ]
