# Generated by Django 4.2.7 on 2026-09-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0019_appexecutionagent_health_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appexecutionagent',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agent令牌创建时间'),
        ),
        migrations.AddField(
            model_name='appexecutionagent',
            name='token_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Agent令牌Hash'),
        ),
        migrations.AddField(
            model_name='appexecutionagent',
            name='token_last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agent令牌最后使用时间'),
        ),
        migrations.AddField(
            model_name='appexecutionagent',
            name='token_prefix',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Agent令牌前缀'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='attempt_no',
            field=models.IntegerField(default=0, verbose_name='执行尝试次数'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='execution_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='执行快照'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='last_event_seq',
            field=models.IntegerField(default=0, verbose_name='最近事件序号'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='任务租约到期时间'),
        ),
        migrations.AddField(
            model_name='apptestexecution',
            name='lease_token',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='任务租约令牌'),
        ),
        migrations.AddIndex(
            model_name='apptestexecution',
            index=models.Index(fields=['lease_token'], name='app_test_ex_lease_t_212340_idx'),
        ),
        migrations.AddIndex(
            model_name='apptestexecution',
            index=models.Index(fields=['lease_expires_at'], name='app_test_ex_lease_e_374442_idx'),
        ),
    ]
